### ISSUE TITLE
有办法在弹出的视图 !!外部!! 的任意位置单击时 退出视图 吗?

### ISSUE THREAD

**Issue by dyguests** [pljhonglu/LewPopupViewController#1]
你好,感谢你,这个控件很好用,而且很简洁...

我想实现 在且仅在 弹出视图外部 单击时退出视图
或者点击Close按钮时 退出视图.请问有什么办法吗?

或者说, 至少让控件在在弹出视图内部点击时不会退出..

www..

**Comment by pljhonglu** [comment]
这个确实是个 bug，我已经修改了，请下载最新的吧~
感谢支持~
