### ISSUE TITLE
请问，你这个pop出来的View，必须是单例么?pop出来的View自定义加入的控件点击无反应。能解答下么？

### ISSUE THREAD

**Issue by jaccty** [pljhonglu/LewPopupViewController#6]

**Comment by pljhonglu** [comment]
请贴一下使用时的代码

**Comment by xuyuchenglan** [comment]
您好，为什么我使用您的框架，试图弹出后就消失不了了呀？

**Comment by xuyuchenglan** [comment]
移除弹出视图的代码如下：`- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {

```
    _innerView = [[UIView alloc] initWithFrame:frame];
    [self addSubview:_innerView];


    //添加一个观察者，以移除蒙布视图
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(removeCyanView) name:@"removeCyanView" object:nil];

}
return self;
```

}

//移除蒙布视图
- (void)removeCyanView
  {
  NSLog(@"移除蒙布视图");
  [_parentVC lew_dismissPopupView];
  }

/////移除观察者
- (void)dealloc
  {
  [[NSNotificationCenter defaultCenter] removeObserver:self name:@"removeCyanView" object:nil];
  }
  `

**Comment by xuyuchenglan** [comment]
弹出视图时的代码如下:
`[self lew_presentPopupView:_viewPreview animation:[LewPopupViewAnimationFade new]  dismissed:^{
        
        NSLog(@"扫描二维码结束,fade");
        
    }];`

**Comment by xuyuchenglan** [comment]
弹出视图时的代码如下:
`
[self lew_presentPopupView:_viewPreview animation:[LewPopupViewAnimationFade new] dismissed:^{

```
NSLog(@"扫描二维码结束,fade");
```

}];
`

**Comment by xuyuchenglan** [comment]
大神，急求您的解救，从昨天下午开始，就一直解决不靠这个问题~

**Comment by pljhonglu** [comment]
好的，稍等，我测试一下看看

**Comment by pljhonglu** [comment]
@xuyuchenglan  弹出视图时有设置 _viewPreview 的 parentVC 么？
